services:
  helloworld:
    image: ghcr.io/mikkelrlarsen/helloworld:latest
    restart: unless-stopped
    ports:
     - 8080:8080

    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "dotnet", "HelloWorld.dll"]
      interval: 30s
      timeout: 3s
      retries: 3

  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: "true"
    command: --label-enable