name: Build and Push .NET Container Image
on:
  push:
    branches: [ "WithoutDockerfile" ]

env:
  OWNER: mikkelrlarsen
  IMAGE: ghcr.io/${{ env.OWNER }}/helloworld:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish .NET project as container
        working-directory: ./CiCD
        run: |
          dotnet publish -c Release -t:PublishContainer \
            -p:ContainerRegistry=ghcr.io \
            -p:ContainerImageName=${{ env.IMAGE }} \
            --os linux --arch amd64,arm64
